
# # ----------------------------------------------------------------
# # Course: EECS 110, Northwestern University
# # Term: Winter 2019
# # Autogenerated from: "05. Modules.ipynb"
# # 
# # Note: Each example is commented out. To uncomment, highlight
# # the area you want to uncomment and type "cmd /" (which both adds
# # and removes comments).
# # ----------------------------------------------------------------




# # --------------------------------------------------------------------------------
# # # MODULES
# # References:
# # * https://docs.python.org/3/tutorial/modules.html 
# # 
# # **From the Python.org tutorial:**  Python has a way to put definitions in a file and use them in a script or in an interactive instance of the interpreter. Such a file is called a module; definitions from a module can be imported into other modules or into the main module (the collection of variables that you have access to in a script executed at the top level and in calculator mode).
# # 
# # Modules come from a variety of different sources. Some modules, called "built-in modules" come with the Python language. Others, such as matplotlib, are created by other people and organizations. These are called "third party modules / libraries." Still other modules are those you make yourself. We will be using all three kinds of modules in this notebook.
# # 
# # 1. Built-In Modules
# # 2. Third Party Modules
# # 3. Your Modules
# # --------------------------------------------------------------------------------




# # --------------------------------------------------------------------------------
# # ## 1. Built-In Modules
# # --------------------------------------------------------------------------------




# # --------------------------------------------------------------------------------
# # ## 2. Third Party Modules
# # --------------------------------------------------------------------------------




# # --------------------------------------------------------------------------------
# # ## 3. Your Own Modules
# # --------------------------------------------------------------------------------








