# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EECS 110
email: vanwars@northwestern.edu
description: >- # this means to ignore newlines until "baseurl:"
  EECS Description
baseurl: "/eecs110" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  vanwars

# Build settings
markdown: kramdown
theme: "just-the-docs"
remote_theme: "pmarsceill/just-the-docs"
search_enabled: true

aux_links:
    "Piazza":
      - "//piazza.com/northwestern/winter2019/eecs110/home"

